# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e954bc7bf3e2c05da1f4b8e10f07b7603f92c0b4a6b02e0d518940c0fabbbd2fc2afbc0ca84bead9613bc137938c5952aae1a16e1a72a8519c8ef12b176079b7

test:
  secret_key_base: dc2cafea716fe81b309e8cd01a0d1e24333db66c078ed0000533ca73821e899089d4f15051caf719f5757d75ea616e46f9d31273c75892b19f2a9f35649fff93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
